# Generated by Django 6.0 on 2026-01-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_patient_appointment'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuespecialtymap',
            name='issue_term',
            field=models.CharField(help_text="e.g., 'Broken leg', 'Flu'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='issuespecialtymap',
            name='primary_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_issues', to='hospitals.specialty'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_app_records', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_issue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Assignment'), ('IN', 'Admitted (In-Patient)'), ('OUT', 'Discharged (Out-Patient)')], default='PENDING', max_length=10),
        ),
    ]
